function grad_h = grad_h_calc(in1,alpha_sum,D_s)
%GRAD_H_CALC
%    GRAD_H = GRAD_H_CALC(IN1,ALPHA_SUM,D_s)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Aug-2025 01:31:31

p1_1 = in1(:,1);
p1_2 = in1(:,3);
p2_1 = in1(:,2);
p2_2 = in1(:,4);
v1_1 = in1(:,5);
v1_2 = in1(:,7);
v2_1 = in1(:,6);
v2_2 = in1(:,8);
t2 = -p1_2;
t3 = -p2_2;
t4 = -v1_2;
t5 = -v2_2;
t6 = sqrt(2.0);
t7 = p1_1+t2;
t8 = p2_1+t3;
t9 = t4+v1_1;
t10 = t5+v2_1;
t11 = abs(t7);
t12 = abs(t8);
t13 = sign(t7);
t14 = sign(t8);
t17 = t7.*t9;
t18 = t8.*t10;
t15 = t11.^2;
t16 = t12.^2;
t24 = t17+t18;
t19 = t15+t16;
t20 = sqrt(t19);
t21 = 1.0./t20;
t23 = -t20;
t22 = t21.^3;
t25 = D_s+t23;
t27 = t7.*t21;
t28 = t8.*t21;
t29 = t9.*t21;
t30 = t10.*t21;
t26 = alpha_sum.*t25;
t33 = t11.*t13.*t22.*t24;
t34 = t12.*t14.*t22.*t24;
t31 = -t26;
t32 = 1.0./sqrt(t31);
t35 = (alpha_sum.*t6.*t11.*t13.*t21.*t32)./2.0;
t36 = (alpha_sum.*t6.*t12.*t14.*t21.*t32)./2.0;
grad_h = [t29-t33+t35,t30-t34+t36,-t29+t33-t35,-t30+t34-t36,t27,t28,-t27,-t28];
