function hx = h_calc(in1,alpha_sum,D_s)
%H_CALC
%    HX = H_CALC(IN1,ALPHA_SUM,D_s)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Aug-2025 01:31:31

p1_1 = in1(:,1);
p1_2 = in1(:,3);
p2_1 = in1(:,2);
p2_2 = in1(:,4);
v1_1 = in1(:,5);
v1_2 = in1(:,7);
v2_1 = in1(:,6);
v2_2 = in1(:,8);
t2 = -p1_2;
t3 = -p2_2;
t4 = p1_1+t2;
t5 = p2_1+t3;
t6 = abs(t4);
t7 = abs(t5);
t8 = t6.^2;
t9 = t7.^2;
t10 = t8+t9;
hx = 1.0./sqrt(t10).*(t4.*(v1_1-v1_2)+t5.*(v2_1-v2_2))+sqrt(2.0).*sqrt(-alpha_sum.*(D_s-sqrt(t10)));
